# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    container_name: repress-dev-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: repress-dev
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - 5432:5432

  # adminer:
  #   container_name: repress-dev-adminer
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
