# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    container_name: repress-test-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: repress-test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword

  adminer:
    container_name: repress-test-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
